{{- if .Values.certManager }}
{{- $fullName := include "beacon.fullname" . }}
{{- $labels := include "beacon.labels" . }}
{{- $values := .Values }}
{{- $capabilities := .Capabilities }}
{{- range $service, $settings := .Values.beacon.service }}
{{- if and $settings.tls }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $fullName }}-{{ $service }}-cert
spec:
  secretName: {{ $fullName }}-{{ $service }}-certificate
  issuerRef:
    name: letsencrypt
  dnsNames:
  - {{ $settings.hostname }}
{{- end }}
---
{{- end }}
{{- end }}
