{{- $fullName := include "beacon.fullname" . }}
{{- $labels := include "beacon.labels" . }}
{{- $selectorLabels := include "beacon.selectorLabels" . }}
{{- range $service, $settings := .Values.beacon.service }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-{{ $service }}
  labels:
    {{- $labels | nindent 4 }}
spec:
  type: {{ $settings.type }}
  ports:
    - port: {{ $settings.port }}
      targetPort: {{ $settings.port }}
      protocol: TCP
      name: http
  selector:
    {{- $selectorLabels | nindent 4 }}
---
{{- end }}
