{{- if .Values.certManager }}
{{- $fullName := .Release.Name }} # fixme, find a generic toplevel name
{{- range $service, $settings := .Values.ingressconfig }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $fullName }}-{{ $settings.hostname }}-cert
spec:
  secretName: {{ $fullName }}-{{ $settings.hostname }}-certificate
  issuerRef:
    name: letsencrypt
  dnsNames:
  - {{ $settings.hostname }}
---
{{- end }}
{{- end }}
