{{- $fullName := include "kiebitz.fullname" . }}
{{- $labels := include "kiebitz.labels" . }}
{{- $values := .Values }}
{{- $capabilities := .Capabilities }}
{{- range $service, $settings := .Values.kiebitz.service }}
{{- if and $settings.tls }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $fullName }}-{{ $service }}-cert
spec:
  secretName: {{ $fullName }}-{{ $service }}-certificate
  issuerRef:
    name: letsencrypt
  dnsNames:
  - {{ $settings.hostname }}
{{- end }}
---
{{- end }}