{{- $fullName := include "kiebitz.fullname" . }}
{{- $labels := include "kiebitz.labels" . }}
{{- $selectorLabels := include "kiebitz.selectorLabels" . }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}
  labels:
    {{- $labels | nindent 4 }}
spec:
  type: ClusterIP
  ports:
{{- range $service, $settings := .Values.kiebitz.service }}
    - port: {{ $settings.port }}
      targetPort: http
      protocol: TCP
{{- end }}
  selector:
    {{- $selectorLabels | nindent 4 }}
---