{{- $fullName := include "static.fullname" . }}
{{- $labels := include "static.labels" . }}
{{- $selectorLabels := include "static.selectorLabels" . }}
{{- range $service, $settings := .Values.static.service }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-{{ $service }}
  labels:
    {{- $labels | nindent 4 }}
spec:
  type: {{ $settings.type }}
  ports:
    - port: {{ $settings.port }}
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    {{- $selectorLabels | nindent 4 }}
{{- end }}