apiVersion: v1
kind: Service
metadata:
  name: {{ include "static.fullname" . }}
  labels:
    {{- include "static.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.static.type }}
  ports:
    - port: {{ .Values.service.static.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "static.selectorLabels" . | nindent 4 }}
