# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Create and publish Docker images for apps-inoeg

on:
  push:
    branches:
      - "main"
    tags:
      - "v*"
  pull_request:
    branches:
      - "main"

env:
  REGISTRY: ghcr.io
  BRANCH: 
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/kiebitz-oss/apps-inoeg-main
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha
      - name: Build and push Docker apps-inoeg-main
        uses: docker/build-push-action@v2
        with:
          context: container/apps-inoeg
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.REGISTRY }}/kiebitz-oss/apps-inoeg-main:latest
          labels: ${{ steps.meta.outputs.labels }}
      - name: Retag services-inoeg
        uses: tinact/docker.image-retag@master
        with:
          image_name: kiebitz-oss/services-inoeg
          image_old_tag: main
          image_new_tag: latest
          registry: ghcr.io
          registry_username: ${{ github.actor }}
          registry_password: ${{ secrets.GITHUB_TOKEN }}
