name: Deployment to dev-cd.impfterm.in
on:
  push:
  
jobs:
  job1:
    steps:
    - uses: actions/checkout@v2
    - name: Kuberentes (k8s) cli - kubectl
      uses: actions-hub/kubectl@v1.21.2
      env:
        KUBE_CONFIG: ${{ secrets.KUBECONFIG_PLUSCLOUD }}
      with:
        args: get pods
    - name: Show all pods
      run: kubectl get pods -A
