name: Deployment to dev-cd.impfterm.in
on:
  push:
  
jobs:
  job1:
    runs-on: ubuntu-latest
    env:
      KUBE_CONFIG: ${{ secrets.KUBECONFIG_PLUSCLOUD }}
    steps:
    - uses: actions/checkout@v2
    - name: Kuberentes (k8s) cli - kubectl
      uses: actions-hub/kubectl@v1.21.2
    - name: Show all pods
      run: kubectl get pods -A
