name: Deployment to dev-cd.impfterm.in
on:
  workflow_call:
  workflow_dispatch:
  repository_dispatch:
    types: ["deployment"]

concurrency:
  group: deployment
  cancel-in-progress: true

jobs:
  run-tests:
    runs-on: ubuntu-latest
    env:
      KUBE_CONFIG: ${{ secrets.KUBECONFIG_PLUSCLOUD }}
      KUBECONFIG: /home/runner/work/kubernetes/kubernetes/kubeconfig.yml
    steps:
    - uses: actions/checkout@v2
    - shell: bash
      run: |
        echo "$KUBE_CONFIG" | base64 -d > kubeconfig.yml
    - run: 
        kubectl config set-context --current --namespace=impfen-dev|
        kubectl version --client
    - name: Show all pods
      run: kubectl get pods -A
    - run: helm version
    - name: Get rid of old kiebitz installation if present
      run: | 
        helm uninstall kiebitz-plus
        kubectl wait --for=delete --timeout=60s deployment/kiebitz-plus-static
        kubectl wait --for=delete --timeout=60s deployment/kiebitz-plus-kiebitz
      continue-on-error: true    
    - name: Get rid of old secret if present
      run: kubectl delete secret kiebitz-dev
      continue-on-error: true
    - name: Helm install or upgrade Zalando Postgres
      run: |
        echo DISABLED Zalando Postgres Operator
        # echo see https://github.com/zalando/postgres-operator/blob/master/docs/quickstart.md#manual-deployment-setup
        #git clone https://github.com/zalando/postgres-operator.git

        # echo see https://github.com/zalando/postgres-operator/blob/master/docs/quickstart.md#helm-chart
        # helm upgrade --install postgres-operator ./postgres-operator/charts/postgres-operator
        
    - name: Helm install Application
      run: |
        echo Install secret
        (
          cd settings/dev
          kubectl create secret generic kiebitz-dev \
             --from-file=001_default.yml \
             --from-file=002_admin.json \
             --from-file=003_appt.json \
             --from-file=004_storage.json \
             --from-file=secret-mediator-keys
        )
        
        
        helm install kiebitz-plus --values=charts/kiebitz/values-plus.yaml ./charts/kiebitz

        cat <<EOF
        
        waiting for deployments getting available
        
        EOF
        sleep 10
        kubectl get all
        kubectl describe pods
        kubectl logs -l "app.kubernetes.io/name=kiebitz,app.kubernetes.io/instance=kiebitz-plus"
        kubectl wait --for=condition=available --timeout=60s deployment/kiebitz-plus-static
        kubectl wait --for=condition=available --timeout=60s deployment/kiebitz-plus-kiebitz
        
        kubectl exec db-redis-ha-server-0 -c redis -- redis-cli -c -h db-redis-ha-haproxy flushall sync
        kubectl exec `kubectl get pod -l app.kubernetes.io/name=kiebitz -o jsonpath='{.items[0].metadata.name}'` /kiebitz admin mediators upload /settings/secret-mediator-keys
        kubectl exec db-redis-ha-server-0 -c redis -- redis-cli -c -h db-redis-ha-haproxy keys '*'
