name: Deployment to dev-cd.impfterm.in
on:
  push:
  
jobs:
  job1:
    runs-on: ubuntu-latest
    env:
      KUBE_CONFIG: ${{ secrets.KUBECONFIG_PLUSCLOUD }}
      KUBECONFIG: kubeconfig.yml
    steps:
    - shell: bash
      run: |
        echo "$KUBE_CONFIG" | base64 -d > kubeconfig.yml
    - run: kubectl version --client
    - name: Show all pods
      run: kubectl get pods -A
    - run: helm version
