name: Minikube Helm Deployment
on:
  push:
    branches: [ main ]
# re-enable once we stop pull requests from triggering deployments
#  pull_request:
#    branches: [ main ]
  repository_dispatch:
    types: ["deployment"]
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    name: build example and deploy to minikube
    steps:
    - uses: actions/checkout@v2
    - name: Start minikube
      uses: medyagh/setup-minikube@master
    - name: Show all pods
      run: kubectl get pods -A
    - name: List contents
      run: |
        pwd
        ls -R .
    - name: Install Helm
      uses: azure/setup-helm@v1
      with:
        version: v3.4.0
    - name: Docker Login to ghcr.io
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Helm install Redis
      run: |
        helm repo add dandydev https://dandydeveloper.github.io/charts
        helm install meter --set replicas=1 dandydev/redis-ha
        helm install db --set replicas=1 dandydev/redis-ha
        
        helm ls
        
        cat <<EOF
        
        waiting for Redis pods to become ready
        
        EOF

        kubectl wait -l statefulset.kubernetes.io/pod-name=meter-redis-ha-server-0 --for=condition=ready pod --timeout=-1s
        kubectl wait -l statefulset.kubernetes.io/pod-name=db-redis-ha-server-0 --for=condition=ready pod --timeout=-1s

    - name: Helm install Application
      run: |
        echo Install secret
        (
          cd settings/dev
          kubectl create secret generic kiebitz-dev \
             --from-file=001_default.yml \
             --from-file=002_admin.json \
             --from-file=003_appt.json \
             --from-file=004_storage.json
        )
        
        
        helm install kiebitz-minikube ./charts/kiebitz
        
        cat <<EOF
        
        waiting for deployments getting available
        
        EOF

        sleep 10
        kubectl get all
        kubectl describe pods
        kubectl logs -l "app.kubernetes.io/name=kiebitz,app.kubernetes.io/instance=kiebitz-minikube"

        kubectl wait --for=condition=available --timeout=60s deployment/kiebitz-minikube-static
        kubectl wait --for=condition=available --timeout=60s deployment/kiebitz-minikube-kiebitz

        kubectl get all
    - name: Helm tests
      run: |
        helm test kiebitz-minikube --debug --logs
    - name: Dispatch raw deployment
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.PAT_FOR_WORKFLOW }}
        event-type: raw-deployment
